//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverScoring.DBModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Анкета
    {
        [Key]
        public long АнкетаID { get; set; }
        public Nullable<long> ВодительID { get; set; }
        public Nullable<long> Возраст { get; set; }
        public Nullable<long> Дети { get; set; }
        public Nullable<long> СемейноеПоложение { get; set; }
        public Nullable<long> ЕстьКредит { get; set; }
        public Nullable<long> КредитнаяИстория { get; set; }
        public Nullable<long> Доход { get; set; }
        public Nullable<long> Трудоустройство { get; set; }
        public Nullable<long> НаличиеМашины { get; set; }
        public Nullable<long> АварииЗаПятьЛет { get; set; }
        public Nullable<long> СтажРаботы { get; set; }
        public Nullable<long> СтажВождения { get; set; }

        public virtual Водители Водители { get; set; }
    }
}
