//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverScoring.DBModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Запросы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Запросы()
        {
            this.РезультатЗапроса = new HashSet<РезультатЗапроса>();
        }

        [Key]
        public long ЗапросID { get; set; }
        public string ДатаЗапроса { get; set; }
        public string ВремяПолученияМашины { get; set; }
        public string ВремяВыдачиМашины { get; set; }
        public Nullable<long> МашинаID { get; set; }
        public Nullable<long> ВодительID { get; set; }
        public Nullable<long> ЗапросРассмотрен { get; set; }

        public virtual Водители Водители { get; set; }
        public virtual Машины Машины { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезультатЗапроса> РезультатЗапроса { get; set; }
    }
}
