//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverScoring.DBModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Машины
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Машины()
        {
            this.Запросы = new HashSet<Запросы>();
            this.Фотографии = new HashSet<Фотографии>();
        }

        [Key]
        public long МашинаID { get; set; }
        public Nullable<long> МодельID { get; set; }
        public Nullable<long> СостояниеID { get; set; }
        public Nullable<long> MinScore { get; set; }
        public Nullable<long> СтоимостьЧас { get; set; }
        public string Номер { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Запросы> Запросы { get; set; }
        public virtual МоделиМашин МоделиМашин { get; set; }
        public virtual Состояния Состояния { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Фотографии> Фотографии { get; set; }
    }
}
