//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverScoring.DBModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class РезультатЗапроса
    {
        [Key]
        public long РезультатID { get; set; }
        public Nullable<long> АналитикID { get; set; }
        public Nullable<long> МашинаВыдана { get; set; }
        public string ПричинаОтказа { get; set; }
        public Nullable<long> ЗапросID { get; set; }

        public virtual Аналитики Аналитики { get; set; }
        public virtual Запросы Запросы { get; set; }
    }
}
