//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverScoring.DBModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Фотографии
    {
        [Key]
        public long ФотоID { get; set; }
        public Nullable<long> МашинаID { get; set; }
        public byte[] Фото { get; set; }

        public virtual Машины Машины { get; set; }
    }
}
