//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverScoring.DBModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Штрафы
    {
        [Key]
        public long ШтрафID { get; set; }
        public Nullable<long> ВодительID { get; set; }
        public string ДополнительнаяИнформация { get; set; }
    
        public virtual Водители Водители { get; set; }
    }
}
